-- Seed 9 Tajna Botanika products
INSERT INTO products (name, slug, description, price, stock, category, image_url, thc_percent, cbd_percent, cbg_percent, thc_x_percent, effects, flavor_profile, featured, is_popular, gram_options, color_accent, glow_color)
VALUES
  ('Golden Nugget', 'golden-nugget', 'Sladký a ovocný strain s vysokým obsahem THC-X. Intenzivní relaxace a euforie.', 190, 100, 'flower', '/images/golden-nugget.webp', 0.06, 9.05, 0.1, 40, ARRAY['relaxace', 'euforie', 'kreativita'], 'Sladký, ovocný, zemitý', true, true, ARRAY[1, 3, 5, 10], '#FFD700', '#FFD700'),
  ('Amnesia', 'amnesia', 'Legendární sativa-dominantní strain. Silný cerebrální efekt a energizující účinky.', 190, 100, 'flower', '/images/amnesia.webp', 0.05, 8.5, 0.15, 45, ARRAY['energie', 'fokus', 'kreativita'], 'Citrusový, hazy, kořenitý', true, false, ARRAY[1, 3, 5, 10], '#00FF88', '#00FF88'),
  ('Pineapple Zkittlez', 'pineapple-zkittlez', 'Tropický a ovocný hybrid s vyváženými účinky. Ideální na odpolední relaxaci.', 190, 100, 'flower', '/images/pineapple-zkittlez.webp', 0.04, 10.2, 0.2, 38, ARRAY['relaxace', 'nálada', 'chuť'], 'Ananas, bonbóny, tropické ovoce', true, false, ARRAY[1, 3, 5, 10], '#FF6B35', '#FF6B35'),
  ('Gelato', 'gelato', 'Prémiový hybrid známý svou sladkou chutí a silnými relaxačními účinky.', 190, 100, 'flower', '/images/gelato.webp', 0.06, 11.0, 0.12, 42, ARRAY['relaxace', 'euforie', 'spánek'], 'Sladký, vanilkový, krémový', true, true, ARRAY[1, 3, 5, 10], '#9B59B6', '#9B59B6'),
  ('Lemon Cherry Gelato', 'lemon-cherry-gelato', 'Exkluzivní strain s jedinečnou kombinací citrusových a třešňových tónů.', 190, 100, 'flower', '/images/lemon-cherry-gelato.webp', 0.05, 9.8, 0.18, 44, ARRAY['relaxace', 'nálada', 'kreativita'], 'Citron, třešeň, krémový', true, false, ARRAY[1, 3, 5, 10], '#E74C3C', '#E74C3C'),
  ('Bubble Gum', 'bubble-gum', 'Klasický strain se sladkou žvýkačkovou chutí. Příjemná a vyrovnaná relaxace.', 190, 100, 'flower', '/images/bubble-gum.webp', 0.04, 8.0, 0.1, 35, ARRAY['relaxace', 'nálada', 'sociální'], 'Žvýkačka, sladký, ovocný', true, false, ARRAY[1, 3, 5, 10], '#FF69B4', '#FF69B4'),
  ('Forbidden Fruit', 'forbidden-fruit', 'Exotický indica strain s hlubokými relaxačními účinky a ovocným aroma.', 190, 100, 'flower', '/images/forbidden-fruit.webp', 0.06, 12.0, 0.25, 40, ARRAY['hluboká relaxace', 'spánek', 'úleva'], 'Třešeň, mango, citrus', true, false, ARRAY[1, 3, 5, 10], '#8B0000', '#8B0000'),
  ('Wedding Cake', 'wedding-cake', 'Luxusní hybrid s bohatou chutí vanilky a pepře. Silná relaxace těla.', 190, 100, 'flower', '/images/wedding-cake.webp', 0.05, 10.5, 0.15, 43, ARRAY['relaxace', 'euforie', 'úleva od bolesti'], 'Vanilka, pepř, zemitý', true, false, ARRAY[1, 3, 5, 10], '#F5F5DC', '#F5F5DC'),
  ('Blue Dream', 'blue-dream', 'Populární sativa hybrid s vyváženými účinky. Jemná relaxace s cerebrální stimulací.', 190, 100, 'flower', '/images/blue-dream.webp', 0.05, 9.5, 0.14, 41, ARRAY['relaxace', 'kreativita', 'fokus'], 'Borůvka, sladký, vanilka', true, true, ARRAY[1, 3, 5, 10], '#4169E1', '#4169E1')
ON CONFLICT (slug) DO NOTHING;
